from setuptools import setup
from champ.constants import VERSION
import git

repo = git.Repo(search_parent_directories=True)
sha = repo.head.object.hexsha

# automatically update the variable containing the git commit so we can keep track of which version of the software
# was used to run analyses
with open("champ/__init__.py", "w") as f:
    f.write("# This file is automatically generated by setup.py. Do not modify it.\n")
    f.write("git_commit = '%s'\n" % sha)


if __name__ == '__main__':
    setup(
        name='champ',
        packages=['champ', 'champ.controller'],
        version=VERSION,
        entry_points={
          'console_scripts': [
              'champ = champ.main:main'
          ]
        },
        include_package_data=True,
        zip_safe=False,
        data_files=[('notebooks', ['notebooks/intensity-and-kd-fitting.ipynb',
                                   'notebooks/genome-analysis.ipynb',
                                   'notebooks/synthetic-library-analysis.ipynb']),

                    ],
        description='Processes CHAMP image data',
        url='http://www.finkelsteinlab.org',
        keywords=['DNA', 'protein', 'illumina', 'bioinformatics', 'CRISPR'],
        classifiers=['Development Status :: 3 - Alpha',
                     'Natural Language :: English',
                     'Intended Audience :: Science/Research',
                     'License :: Freely Distributable',
                     'Operating System :: POSIX :: Linux',
                     'Programming Language :: Python :: 2.7',
                     'Topic :: Scientific/Engineering :: Bio-Informatics',
                     ]
    )
